allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bigint-buffer: true
  bufferutil: true
  keccak: true
  msgpackr-extract: true
  prisma: true
  secp256k1: true
  unrs-resolver: true
  utf-8-validate: true
