FROM node:22-alpine
WORKDIR /app

RUN corepack enable pnpm && apk add --no-cache wget ca-certificates tzdata git

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma ./prisma/
COPY tsconfig.json nest-cli.json ./
RUN pnpm install --frozen-lockfile
RUN npx prisma generate

EXPOSE 3000
