FROM node:22-alpine
WORKDIR /app

RUN npm install -g pnpm@11.0.8 && apk add --no-cache wget ca-certificates tzdata git

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma ./prisma/
COPY tsconfig.json nest-cli.json ./
RUN --mount=type=cache,target=/pnpm-store \
    pnpm install --frozen-lockfile --store-dir /pnpm-store
RUN npx prisma generate

EXPOSE 3000
