FROM node:22-alpine
WORKDIR /app

RUN npm install -g pnpm@11.0.8
RUN apk add --no-cache wget ca-certificates tzdata git || (sleep 3 && apk update && apk add --no-cache wget ca-certificates tzdata git)

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma ./prisma/
COPY tsconfig.json nest-cli.json ./
RUN mkdir -p /pnpm-store && pnpm config set store-dir /pnpm-store && pnpm config set fetch-timeout 300000
RUN for i in 1 2 3; do pnpm i --frozen-lockfile && break || sleep 10; done
RUN for i in 1 2 3; do npx --yes prisma generate && break || sleep 10; done

EXPOSE 3000
