name: Issue SSL Cert via acme.sh

on:
  workflow_dispatch:
    inputs:
      txt1:
        description: '_acme-challenge.api.useherald.xyz TXT value'
        required: false
      txt2:
        description: '_acme-challenge.api.register.useherald.xyz TXT value'
        required: false

jobs:
  issue-cert:
    runs-on: ubuntu-latest
    steps:
      - name: Install acme.sh
        run: curl https://get.acme.sh | sh -s email=herald.admin@gmail.com

      - name: Issue cert (pre-added DNS records)
        run: |
          ~/.acme.sh/acme.sh --issue \
            --dns \
            -d api.useherald.xyz \
            -d api.register.useherald.xyz \
            --yes-I-know-dns-manual-mode-enough-go-ahead-please

      - name: Print base64 certs
        run: |
          echo "=== FULLCHAIN ==="
          cat ~/.acme.sh/api.useherald.xyz/fullchain.cer | base64 -w 0
          echo ""
          echo "=== KEY ==="
          cat ~/.acme.sh/api.useherald.xyz/api.useherald.xyz.key | base64 -w 0